nodeLinker: node-modules
nmHoistingLimits: workspaces

npmScopes:
  ducky0203:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: "${PACKAGE_TOKEN-}"

yarnPath: .yarn/releases/yarn-4.11.0.cjs
